import { InvestmentWithUser } from './investment.interface';

export interface ProjectFormValues {
  title: string;
  description: string;
  address: string;
  projectValueTotal: number;
  startIncomeDate?: Date;
  endIncomeDate?: Date;
  country: string;
  department: string;
  city: string;
  minInvestmentAmount: number;
  propertyType: 'viviendaDeInteresSocial' | 'viviendaDeInteresPrioritario';
  squareMeters: number;
  bedrooms: number;
  bathrooms: number;
  rentalYieldsAnnualCash?: number;
  incomeFromValuationAnnualCash?: number;
  builder?: string;
  commonAreas: string[];
  projectLinks?: string;
  totalPropertyCost?: number;
  finishingCost?: number;
  basicEquipmentAndTestingCost?: number;
  legalCost?: number;
  cetificatesSNandRCost?: number;
  studyTitleCost?: number;
  companiesIncorporationCost?: number;
  accountServicesCost?: number;
  propertyAppraisal?: number;
  transactionCost?: number;
  searchAndAdvertisingFee?: number;
  contigenciesFee?: number;
}

export interface ProjectWithInvestmentsAndUsers {
  title: string;
  address: string;
  description?: string;
  projectValueTotal?: number;
  projectValueActual?: number;
  media: string[];
  documents: any[];
  createdAt: Date;
  updatedAt: Date;
  accountServicesCost?: number;
  basicEquipmentAndTestingCost?: number;
  bathrooms: number;
  bedrooms: number;
  builder?: string;
  cetificatesSNandRCost?: number;
  city: string;
  commonAreas: string[];
  companiesIncorporationCost?: number;
  contigenciesFee?: number;
  country: string;
  department: string;
  endIncomeDate?: Date;
  finishingCost?: number;
  incomeFromValuationAnnualCash?: number;
  legalCost?: number;
  projectLinks?: string;
  propertyAppraisal?: number;
  propertyType: string;
  rentalYieldsAnnualCash?: number;
  searchAndAdvertisingFee?: number;
  squareMeters: number;
  startIncomeDate?: Date;
  studyTitleCost?: number;
  totalPropertyCost?: number;
  transactionCost?: number;
  status: string;
  projectId: number;
  minInvestmentAmount: number;
  Investment: InvestmentWithUser[];
}
